name: "Azure_Backend_Git_Actions"
on:
    push:
        branches:
            - main
jobs:
    auth:
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
            ARM_CLIENT_SCERET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
            ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: az login
              uses: azure/login@v1
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}

            - name: 'Terraform Format'
              uses: hashicorp/setup-terraform@v2.0.2
            - name: terraform Init,plan and apply
              run: |
                 cd Terraform
                 echo `pwd`
                 echo "tfpath ${{ github.event.inputs.tfpath }}"
                 echo "** Running Terraform Init**"
                 terraform init

                 echo "** Running Terraform Format**"
                 terraform fmt

                 echo "** Running Terraform Validate**"
                 terraform validate

                 echo "** Running Terraform Plan**"
                 terraform plan

                 echo "** Runnning Terraform Apply**"
                 terraform apply -auto-approve
              working-directory: ${{github.event.inputs.tfpath}}
            - name: Terraform Destroy
              run: |
                 echo "** Running Terraform Destroy**"
                 terraform plan -destroy
         #        terraform destroy -auto-approve
              working-directory: ${{ github.event.inputs.tfpath }}
            - name: az Logout
              run: |
                 az logout
              if: always()

    bicep:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
